config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'guest_regs#new'

  resources :guest_regs, param: :uuid do
    member do
      post :approve
    end

    collection do
      get :sent
      get :approved
      post :confirm
    end
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest_reg.rb
class GuestReg < ApplicationRecord
  class RegistrationAlreadyApprovedError < StandardError; end
  class RegistrationExpiredError < StandardError; end
  class RegistrationNotApprovedError < StandardError; end

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  EXCLUDE_ATTRIBUTES = %w{uuid username not_before approved approved_at updated_at}

  validates :full_name, presence: true
  validates :organization, presence: true
  validates :email, presence: true, format: { with: EMAIL_REGEX }
  validates :alt_email, allow_blank: true, format: { with: EMAIL_REGEX }
  validates :purpose, presence: true
  validates :escort, presence: true

  before_create do
    prefix = IwaoConfig.fetch(:radius_username_prefix)
    suffix = IwaoConfig.fetch(:radius_username_suffix)

    self.uuid = SecureRandom.uuid.tr('-', '')
    self.username = "#{prefix}#{Digest::SHA256.hexdigest(self.email)[0, 5]}#{suffix}"
    self.not_after = Date.today.end_of_day
  end

  def to_param
    uuid
  end

  def to_s
    s = ""

    self.attributes.each do |key, value|
      next if EXCLUDE_ATTRIBUTES.include?(key)
      next if key == "alt_email" && value.blank?
      s << "#{I18n.t("activerecord.attributes.guest_reg.#{key}")}:\n\t#{value}\n"
    end
    s
  end

  def approved?
    self.approved
  end

  def approve
    raise RegistrationAlreadyApprovedError if self.approved?
    raise RegistrationExpiredError if self.expired?

    self.approved = true
    self.approved_at = Time.zone.now
    create_radius_user
    self.save
  end

  def expired?
    self.not_after < Time.now
  end

  def radius_password
    return unless self.approved?

    f = Fradium.new(Rails.application.credentials.radius)
    raduser = f.find_user(self.username)
    raduser.first[:value]
  end

  private

  def create_radius_user
    f = Fradium.new(Rails.application.credentials.radius)
    raduser = f.find_user(self.username)

    if raduser&.count == 0
      f.create_user(self.username)
    else
      f.modify_user(self.username)
    end

    f.set_expiration(self.username, self.not_after.to_time)
  end
end

app/models/iwao_config.rb
class IwaoConfig < ApplicationRecord
  serialize :content

  def self.fetch(name)
    IwaoConfig.find_by(name: name)&.content
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/guest_regs_controller.rb
class GuestRegsController < ApplicationController
  before_action :set_guest_reg, only: [:show, :edit, :update, :destroy, :approve]

  # GET /guest_regs
  # GET /guest_regs.json
  def index
    @guest_regs = GuestReg.all
    # temporarily disabled
    redirect_to new_guest_reg_url, status: :see_other
  end

  # GET /guest_regs/1
  # GET /guest_regs/1.json
  def show
  end

  # GET /guest_regs/new
  def new
    @guest_reg = GuestReg.new
  end

  # GET /guest_regs/1/edit
  def edit
  end

  # GET /guest_regs/sent
  def sent
  end

  # GET /guest_regs/approved
  def approved
  end

  def approve
    if @guest_reg.approved?
      redirect_to @guest_reg and return
    end

    if @guest_reg.approve
      notifier = GuestRegNotifier.new(@guest_reg)
      notifier.slack_approved
      notifier.email_registration_approved
    end

    redirect_to approved_guest_regs_path
  end

  # GET /guest_regs/confirm
  def confirm
    @guest_reg = GuestReg.new(guest_reg_params)

    if @guest_reg.invalid?
      render :new
    end
  end


  # POST /guest_regs
  # POST /guest_regs.json
  def create
    @guest_reg = GuestReg.new(guest_reg_params)

    if params[:back]
      render :new and return
    end

    if !verify_recaptcha(model: @guest_reg)
      render :confirm and return
    end

    respond_to do |format|
      if @guest_reg.save
        notifier = GuestRegNotifier.new(@guest_reg)
        notifier.slack_request_for_approval
        notifier.email_request_for_approval
        notifier.email_registration_receipt

        if IwaoConfig.fetch(:automatic_approval_enable)
          if @guest_reg.approve
            notifier.slack_approved
            notifier.email_registration_approved
          end
        end

        format.html { redirect_to sent_guest_regs_url, status: :see_other }
        format.json { render :show, status: :created, location: @guest_reg }
      else
        format.html { render :new }
        format.json { render json: @guest_reg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guest_regs/1
  # PATCH/PUT /guest_regs/1.json
  def update
    respond_to do |format|
      if @guest_reg.update(guest_reg_params)
        format.html { redirect_to @guest_reg, notice: 'Guest reg was successfully updated.' }
        format.json { render :show, status: :ok, location: @guest_reg }
      else
        format.html { render :edit }
        format.json { render json: @guest_reg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guest_regs/1
  # DELETE /guest_regs/1.json
  def destroy
    @guest_reg.destroy
    respond_to do |format|
      format.html { redirect_to guest_regs_url, notice: 'Guest reg was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guest_reg
      @guest_reg = GuestReg.find_by!(uuid: params[:uuid])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guest_reg_params
      params.require(:guest_reg).permit(:full_name, :organization, :email, :alt_email, :purpose, :escort, :not_before, :not_after, :approved, :approved_at, :uuid)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/common_marker_helper.rb
module CommonMarkerHelper
  def markdown2html(mdtext)
    CommonMarker.render_html(mdtext)
  end
end

app/helpers/guest_regs_helper.rb
module GuestRegsHelper
end

app/views/guest_regs/_form.html.slim
= form_for @guest_reg, html: { class: "form form-horizontal guest_reg" }, url: { action: :confirm } do |f|
  - if @guest_reg.errors.any?
    .alert.alert-danger
      ul
        - @guest_reg.errors.full_messages.each do |error|
          li= error

  .form-group
    = f.label :full_name, class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :full_name, class: 'form-control', placeholder: t('activerecord.placeholders.guest_reg.full_name')
  .form-group
    = f.label :organization, class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :organization, class: 'form-control', placeholder: t('activerecord.placeholders.guest_reg.organization')
  .form-group
    = f.label :email, class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :email, class: 'form-control', placeholder: t('activerecord.placeholders.guest_reg.email')
  .form-group
    = f.label :alt_email, class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :alt_email, class: 'form-control', placeholder: t('activerecord.placeholders.guest_reg.alt_email')
  .form-group
    = f.label :purpose, class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :purpose, class: 'form-control', placeholder: t('activerecord.placeholders.guest_reg.purpose')
  .form-group
    = f.label :escort, class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :escort, class: 'form-control', placeholder: t('activerecord.placeholders.guest_reg.escort')
  .form-group
    label.col-md-2.control-label
      = t('helpers.label.term_of_service')
    .col-md-10
      == markdown2html(IwaoConfig.fetch(:term_of_service))
  .form-group
    .col-md-offset-2.col-md-10
      == markdown2html(IwaoConfig.fetch(:new_guest_reg_note))
  .form-group
    .col-md-offset-2.col-md-10
      = f.submit nil, :class => 'btn btn-primary'

app/views/guest_regs/approved.html.slim
- model_class = GuestReg
.page-header
  h1=t '.title', :default => ['%{model}'], :model => model_class.model_name.human

.container-fluid
  .row
    .col-lg-12 利用申請を承認しました。

app/views/guest_regs/confirm.html.slim
- model_class = GuestReg
.page-header
  h1=t '.title', :default => [:'helpers.titles.confirm', 'Confirm %{model}'], :model => model_class.model_name.human

.container

  .alert.alert-info 下の内容で申請します。よろしいですか？
  - if @guest_reg.errors.any?
    .alert.alert-danger
      ul
        - @guest_reg.errors.full_messages.each do |error|
          li= error

  = form_for @guest_reg, html: { class: "form form-horizontal guest_reg" } do |f|
    .form-group
      = f.label :full_name, :class => 'control-label col-lg-2'
      .col-lg-10
        = f.text_field :full_name, :class => 'form-control', readonly: true
      = f.error_span(:full_name)
    .form-group
      = f.label :organization, :class => 'control-label col-lg-2'
      .col-lg-10
        = f.text_field :organization, :class => 'form-control', readonly: true
      = f.error_span(:organization)
    .form-group
      = f.label :email, :class => 'control-label col-lg-2'
      .col-lg-10
        = f.text_field :email, :class => 'form-control', readonly: true
      = f.error_span(:email)
    .form-group
      = f.label :alt_email, :class => 'control-label col-lg-2'
      .col-lg-10
        = f.text_field :alt_email, :class => 'form-control', readonly: true
      = f.error_span(:alt_email)
    .form-group
      = f.label :purpose, :class => 'control-label col-lg-2'
      .col-lg-10
        = f.text_field :purpose, :class => 'form-control', readonly: true
      = f.error_span(:purpose)
    .form-group
      = f.label :escort, :class => 'control-label col-lg-2'
      .col-lg-10
        = f.text_field :escort, :class => 'form-control', readonly: true
      = f.error_span(:escort)
    .form-group
      .col-lg-offset-2.col-lg-10
        = recaptcha_tags
    .form-group
      .col-lg-offset-2.col-lg-10
        = f.submit nil, :class => 'btn btn-primary'
        '
        = f.submit t('helpers.links.back'), name: 'back', class: 'btn btn-default'

app/views/guest_regs/edit.html.slim
- model_class = GuestReg
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/guest_regs/index.html.slim
- model_class = GuestReg
.page-header
  h1=t '.title', :default => model_class.model_name.human

table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:full_name)
      th= model_class.human_attribute_name(:organization)
      th= model_class.human_attribute_name(:email)
      th= model_class.human_attribute_name(:purpose)
      th= model_class.human_attribute_name(:escort)
      th= model_class.human_attribute_name(:username)
      th= model_class.human_attribute_name(:not_after)
      th= model_class.human_attribute_name(:approved_at)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @guest_regs.each do |guest_reg|
      tr
        td= guest_reg.full_name
        td= guest_reg.organization
        td
          div= guest_reg.email
          - unless guest_reg.alt_email.blank?
            div= guest_reg.alt_email
        td= guest_reg.purpose
        td= guest_reg.escort
        td= guest_reg.username
        td= guest_reg.not_after
        td= guest_reg.approved_at
        td= guest_reg.created_at
        td
          /= link_to t('.edit', :default => t("helpers.links.edit")), edit_guest_reg_path(guest_reg), :class => 'btn btn-default btn-xs'
          - unless guest_reg.approved?
            = link_to t('.approve', :default => t("helpers.links.approve")), guest_reg_path(guest_reg), :class => 'btn btn-xs btn-success'
            '
            = link_to t('.reject', :default => t("helpers.links.reject")), guest_reg_path(guest_reg), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'
          - else
            .btn.btn-xs.btn-default= t('.approved', :default => t("helpers.links.approved"))

app/views/guest_regs/new.html.slim
- model_class = GuestReg
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human

.container
  = render :partial => "form"

app/views/guest_regs/sent.html.slim
- model_class = GuestReg
.page-header
  h1=t '.title', :default => ['%{model}'], :model => model_class.model_name.human

.col-lg-12 申請を受け付けました。管理者による承認をお待ちください。承認されると、入力メールアドレス宛に接続に必要な情報が送信されます。

app/views/guest_regs/show.html.slim
- model_class = GuestReg
.page-header
  h1=t '.title', :default => model_class.model_name.human

.container-fluid
  .row
    .col-lg-12
      - if @guest_reg.approved?
        .alert.alert-warning
          | この申請は承認済みです
      - elsif @guest_reg.expired?
        .alert.alert-warning
          | この申請は期限切れです
      -else
        .alert.alert-info
          | 以下の利用申請を承認しますか？

  .row
    .col-lg-12
      dl.dl-horizontal

        dt= model_class.human_attribute_name(:full_name)
        dd= @guest_reg.full_name

        dt= model_class.human_attribute_name(:organization)
        dd= @guest_reg.organization

        dt= model_class.human_attribute_name(:email)
        dd= @guest_reg.email

        dt= model_class.human_attribute_name(:alt_email)
        dd= @guest_reg.alt_email

        dt= model_class.human_attribute_name(:purpose)
        dd= @guest_reg.purpose

        dt= model_class.human_attribute_name(:escort)
        dd= @guest_reg.escort

        dt= model_class.human_attribute_name(:not_after)
        dd= @guest_reg.not_after

  .row
    .col-lg-12
      - unless @guest_reg.approved? || @guest_reg.expired?
        = link_to t('.approve', :default => t("helpers.links.approve")), approve_guest_reg_path, method: 'post', class: 'btn btn-success'
        '
        = link_to t('.reject', :default => t("helpers.links.reject")), guest_reg_path(@guest_reg), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'
        '

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "IWAO - Instant Wi-Fi Account Operator"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    /= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    /= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    /= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    /= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    /= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    .navbar.navbar-default.navbar-static-top
        = link_to "IWAO - Instant Wi-Fi Account Operator", root_path, class: 'navbar-brand'

    .container-fluid
      .col-lg-12
        = bootstrap_flash
        = yield

      footer
        p.text-right &copy; 2019 HAW International Inc.